"""Initial alembic..

Revision ID: d87946b1f9de
Revises: c9eea7b66364
Create Date: 2024-04-09 00:39:13.894510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd87946b1f9de'
down_revision: Union[str, None] = 'c9eea7b66364'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'followers_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('users', 'followings_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'followings_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('users', 'followers_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
