"""Initial alembic..

Revision ID: f4d99962c780
Revises: d8aa4783b8a8
Create Date: 2024-04-08 18:00:43.619711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4d99962c780'
down_revision: Union[str, None] = 'd8aa4783b8a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('liked_post_id', sa.Integer(), nullable=True),
    sa.Column('username_like', sa.String(), nullable=True),
    sa.Column('liked_post_image', sa.String(), nullable=True),
    sa.Column('followed_username', sa.String(), nullable=True),
    sa.Column('followed_user_pic', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('activites')
    # ### end Alembic commands ###
